name = "string_ciphers"
description = ""
version = "0.1.0-dev"

authors = ["Juba"]
maintainers = ["Juba <jubakikvadze665@gmail.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["string_ciphers"]
